InferRecordTypes-2.agda:10,7-26: error: [GenericError]
There is no known record with the field x₃
when checking that the expression record { x₃ = Set } has type _1
